---
- name: Remove temporary directory for ssh keys.
  file: 
    path: "{{ sshkey_dir }}"
    state: absent
  become: yes
  delegate_to: localhost

- name: Create temporary directory for ssh keys.
  file: 
    path: "{{ sshkey_dir }}"
    state: directory
    mode: 0755
  delegate_to: localhost

- name: Create ssh key pair.
  community.crypto.openssh_keypair:
    path: "{{ sshkey_dir }}/id_rsa"
  delegate_to: localhost

- name: Create ssh config file.
  blockinfile:
    path: "{{ sshkey_dir }}/config"
    create: yes
    mode: 0600
    block: |
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
  delegate_to: localhost

#- name: Change permission of authorized_keys files
#  file:
#    path: "{{ sshkey_dir }}/authorized_keys"
#    mode: 0600
#  when: inventory_hostname == groups['controller-node'][0]

- name: Copy ssh keys and config files to compute nodes.
  copy:
    src: "{{ sshkey_dir }}/"
    dest: "{{ nova_home }}/.ssh/"
    owner: nova
    group: nova
    mode: preserve
  become: yes
  when: inventory_hostname in groups['compute-node']

- name: Add authorized_keys on compute nodes.
  ansible.posix.authorized_key:
    user: nova
    state: present
    key: "{{ lookup('file', '{{ sshkey_dir }}/id_rsa.pub') }}"
    exclusive: true
  become: true
  when: inventory_hostname in groups['compute-node']

- name: Remove temporary directory for ssh keys.
  file: 
    path: "{{ sshkey_dir }}"
    state: absent
  become: yes
  delegate_to: localhost
...
